volumes:
  mariadb_data: null
  caddy_data: null
  caddy_config: null

services:
  app:
    build: ./app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      DB_HOST: db
      DB_USER: arkservertools
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_DATABASE: arkservertools
      REDIS_HOST: redis
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    restart: unless-stopped
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: arkservertools
      MARIADB_USER: arkservertools
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql