volumes:
  mariadb_data: null
  caddy_data: null
  caddy_config: null

services:
  app:
    build: ./app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - SERVICE_FQDN_APP_80
      - DB_HOST=db
      - DB_USERNAME=${SERVICE_USER_MYSQL}
      - DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      - DB_DATABASE=arkservertools
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-null}
      - MAIL_MAILER=${MAIL_MAILER:-log}
      - MAIL_SCHEME=${MAIL_SCHEME:-null}
      - MAIL_HOST=${MAIL_HOST:-127.0.0.1}
      - MAIL_PORT=${MAIL_PORT:-2525}
      - MAIL_USERNAME=${MAIL_USERNAME:-null}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-null}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-hello@example.com}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-null}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - redis
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - SERVICE_USER_MYSQL=${SERVICE_USER_MYSQL}
      - SERVICE_PASSWORD_MYSQL=${SERVICE_PASSWORD_MYSQL}
      - SERVICE_PASSWORD_MYSQLROOT=${SERVICE_PASSWORD_MYSQLROOT}
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQLROOT}
      - MARIADB_DATABASE=arkservertools
      - MARIADB_USER=${SERVICE_USER_MYSQL}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3