
services:
  app:
    build: ./app/src
    restart: unless-stopped
    expose:
      - "80"
  redis:
    image: redis:latest
    restart: unless-stopped
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - arkservertools_database:/var/lib/mysql