volumes:
  mariadb_data: null
  caddy_data: null
  caddy_config: null

services:
  app:
    build: ./app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - SERVICE_FQDN_APP_80
      - DB_HOST=db
      - DB_USERNAME=${SERVICE_USER_MYSQL}
      - DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      - DB_DATABASE=arkservertools
      - REDIS_HOST=redis
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    restart: unless-stopped
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - SERVICE_USER_MYSQL=${SERVICE_USER_MYSQL}
      - SERVICE_PASSWORD_MYSQL=${SERVICE_PASSWORD_MYSQL}
      - SERVICE_PASSWORD_MYSQLROOT=${SERVICE_PASSWORD_MYSQLROOT}
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQLROOT}
      - MARIADB_DATABASE=arkservertools
      - MARIADB_USER=${SERVICE_USER_MYSQL}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
    volumes:
      - mariadb_data:/var/lib/mysql